### ISSUE TITLE
Any known problem with Bootstrap 4?

### ISSUE THREAD

**Issue by yanezgithub** [moay/afterglow#104]
Hallo, 

is there any known problem using Afterglow with Bootstrap 4? i was using Afterglow correctly but after installing Bootstrap 4 in my project, it doesn't open anymore. 

Thanks

**Comment by moay** [comment]
No known problems, sorry. Let me know if the issue persists. :-)

**Comment by yanezgithub** [comment]
Hallo,

the issue still persists.

I am trying ti use Afterglow class in a “video” html tag inside a Syncfusion dialog box. It worked perfectly up to Bootstrap 3.X but sionce when i have installed in my project Bootstrap4, it doesn’t work anymore.


Keep me updated.


Thanks

Inviato da Posta per Windows 10

Da: moay
Inviato: venerdì 17 gennaio 2020 09:35
A: moay/afterglow
Cc: yanezgithub; Author
Oggetto: Re: [moay/afterglow] Any known problem with Bootstrap 4? (#104)

No known problems, sorry. Let me know if the issue persists. :-)

**Comment by moay** [comment]
Could you share your code? It's not possible to reproduce the problem without seeing some code. Thanks!

**Comment by yanezgithub** [comment]
Hallo, it is complicated to share code but i will send you detailed explanation with some pictures so you can try to reproduce it. The problem could be linked to the chain of javascript libraries loaded into the page. I will let you know soon   Il giorno ven 24 gen 2020 alle ore 15:11 moay <notifications@github.com> ha scritto:Could you share your code? It's not possible to reproduce the problem without seeing some code. Thanks!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.-- Grazie      Stefano Giannotta

**Comment by yanezgithub** [comment]
Hallo, the problem has been solved.  It was nothing about Afterglow itself but it was an old JS library of Syncfusion in my project instead. I have installed now the very last version of Syncfusion JS and CSS library and Afterglow video player work perfectly. Thanks  Inviato da Posta per Windows 10 Da: Stefano GiannottaInviato: venerdì 24 gennaio 2020 16:49A: moay/afterglowCc: moay/afterglow; AuthorOggetto: Re: [moay/afterglow] Any known problem with Bootstrap 4? (#104) Hallo, it is complicated to share code but i will send you detailed explanation with some pictures so you can try to reproduce it. The problem could be linked to the chain of javascript libraries loaded into the page. I will let you know soon   Il giorno ven 24 gen 2020 alle ore 15:11 moay <notifications@github.com> ha scritto:Could you share your code? It's not possible to reproduce the problem without seeing some code. Thanks!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.-- Grazie      Stefano Giannotta
