### ISSUE TITLE
Sleep Mode

### ISSUE THREAD

**Issue by anikahhh** [moay/afterglow#105]
I want to play a short video in loop in fullscreen mode without the sleep mode to turn on. 

I'm simply using the code from the examples? When playing the video on the afterglow website it works fine. What am I missing here?

Thanks for any help

<body>
  <div id="videoContainer">
    <video class="afterglow" autoplay loop id="xmas" width="1920" height="1080" src="someVideo.mp4" type="video/mp4"></video>
  </div>
</body>

**Comment by moay** [comment]
Sleep mode is out of the scope of the video player. Thats something that browsers handle, you won't be able to force them to stay awake with a looping video. You could try to disable looping on the video player and then use events to replay the video when it ended. That could maybe do the trick, let me know if this works.
