### ISSUE TITLE
Uncaught TypeError: afterglow.getPlayer(...).pause is not a function

### ISSUE THREAD

**Issue by romzes2** [moay/afterglow#108]
The following code: 

```
$(document).ready(function(){
	afterglow.getPlayer("UNIQUE_VIDEO_ID").pause();
 });
```

or

```
$( ".afterglow" ).each(function( index ) {
	afterglow.on($(this).attr("id"), 'ready', function(){
		afterglow.getPlayer($(this).attr("id")).pause();
	});
});
```

cause 

Uncaught TypeError: afterglow.getPlayer(...).pause is not a function

Why and how to fix it?

**Comment by moay** [comment]
This is a timing issue. When you call `pause()`, the video has not been initialized, so `afterglow.getPlayer("UNIQUE_VIDEO_ID")` will not return a valid player. Make sure to call `afterglow.init()` before this. Maybe, the `ready` event will help you (http://docs.afterglowplayer.com/docs/events#available-events), as it should allow you to wait for the video to be ready before trying to act on it.

**Comment by romzes2** [comment]
$(window).on('load', function() {});
Should help if some one is still looking the answer.

I migrate to vidoejs since HLS streaming was requared.
