### ISSUE TITLE
How to change YouTube APi controls.

### ISSUE THREAD

**Issue by junglized** [moay/afterglow#110]
Hi,

I was wondering how to disable YT video elements, such as icons in top right-hand corner (share, information, etc) and recommended videos bar, in the plugin?

Thank you!

**Comment by moay** [comment]
Sadly, youtube is pretty limiting their settings and quite unpredictable when adding or removing features. Afterglow was designed to abstract this away, so there currently is no way to change the api behaviour other than documented on http://docs.afterglowplayer.com/
