### ISSUE TITLE
Hi ,please help me.

### ISSUE THREAD

**Issue by DarkPow4** [moay/afterglow#114]
English: Hello, I have been using afterglow for a long time and I feel great and thank you!
I would like to know, is it possible to add in the player the keys "go forward 10 seconds and go back 10 seconds" like youtube?

**Comment by moay** [comment]
Afterglow won't get this feature oob any time soon, but you can of course use the api to build the behaviour. Take a look at http://docs.afterglowplayer.com/docs/api - you should be able to get and set the current time. So get it, add 10 seconds and then set it to that.
