### ISSUE TITLE
Change the position of the controls

### ISSUE THREAD

**Issue by andrecool-68** [moay/afterglow#115]
Play button \ stop in the center of the screen.
Button expand to full screen in the lower right corner.
Progress bar at the bottom of the player.
How can I move the controls?
CSS, HTML, JS are in one file. And I do not know how to move the controls)))

**Comment by moay** [comment]
Hi there. 

I'm very sorry, but your description is not very clear.

> Play button \ stop in the center of the screen.

Yes, that's correct.

> Button expand to full screen in the lower right corner.

Yes, that's correct.

> Progress bar at the bottom of the player.

Yes, that's correct.

> How can I move the controls?

Why? Where? Use CSS.

> CSS, HTML, JS are in one file. And I do not know how to move the controls)))

At runtime: yes. At dev time: no. Checkout the repo, change what you need and go ahead compile your own build. http://docs.afterglowplayer.com/docs/build-your-own
