### ISSUE TITLE
How to change the font family of default control icons

### ISSUE THREAD

**Issue by andrecool-68** [moay/afterglow#116]
The default script  `afterglow.min.js`  uses a  `{font-family:afterglow-icon}`
 please help me switch to `{font-family:VideoJS}`

**Comment by moay** [comment]
http://docs.afterglowplayer.com/docs/build-your-own :-)

**Comment by andrecool-68** [comment]
@moay I downloaded all the + video files to my computer, but the file `afterglow-master\sandbox\index.html`  file does not show the video in the browser.
I changed the path to the video in `index.html`, here is an example `<source src="../video/MP4/afterglow_local.mp4" type="video/mp4"/>`

![1](https://user-images.githubusercontent.com/3471892/83228331-cd4c9e80-a18e-11ea-99cc-43558bc4463e.png)

**Comment by moay** [comment]
Just downloading won't help, you'll have to build. If this is not something you've done before, I suggest you learn more about building javascript projects. The process in itself is described in http://docs.afterglowplayer.com/docs/build-your-own - a basic understanding of how HTML works and how file paths are resolved is required. The issue you describe sounds like you just need to make sure that all video paths are correctly set and that your scripts are running properly - take a look at the JS console to see whats going on.

Sorry, I won't be able to support on how to develop in javascript. :-)

**Comment by andrecool-68** [comment]
@moay  I installed `Node.js + npm`, but as I understood from your link this module is needed to build the project itself? But why the test project does not work.

![Безымянный](https://user-images.githubusercontent.com/3471892/83229597-eeae8a00-a190-11ea-80c8-591e079ba830.png)

![2](https://user-images.githubusercontent.com/3471892/83230257-22d67a80-a192-11ea-86a7-0317c37b0056.png)

**Comment by andrecool-68** [comment]
@moay Changed the path from `../`  on  `./.. /`   now fewer console errors
But still the test page does not work)))

![3](https://user-images.githubusercontent.com/3471892/83232700-3d125780-a196-11ea-8ce6-94ddccd98a44.png)

**Comment by moay** [comment]
Sorry @andrecool-68 , this project is deprecated and I don't currently have the time to support you there. You should make sure to
- Build the project following the documentation
- Sort out your CORS issues by maybe running an actual Testserver

**Comment by andrecool-68** [comment]
@moay I installed Server Apache + PHP on my computer
Please look at the new browser console result.
![4](https://user-images.githubusercontent.com/3471892/83277991-8b961500-a1db-11ea-8845-d51724332893.png)

**Comment by andrecool-68** [comment]
@moay How can I get the afterglow-bundle.js file, because of its absence in the console, this error:
`GET http://localhost:8080/afterglow-master/dist/tmp/afterglow-bundle.js net::ERR_ABORTED 404 (Not Found)`

![6](https://user-images.githubusercontent.com/3471892/83304187-15a7a300-a207-11ea-91d0-51676b5fcce9.png)



This file was created:
```
<!DOCTYPE html>
<html>
<head>
    <title>afterglow development sandbox</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.3">
	
	<!-- STYLES -->
	<link rel="stylesheet"      type="text/css" href="./../vendor/videojs/video-js.css">
	<link rel="stylesheet/less" type="text/css" href="./../src/less/skins/afterglow-default.less">
	<link rel="stylesheet/less" type="text/css" href="./../src/less/skins/afterglow-light.less">
	<link rel="stylesheet/less" type="text/css" href="./../src/less/skins/afterglow-dark.less">
	<link rel="stylesheet/less" type="text/css" href="./../src/less/components/lightbox.less">

	<!-- SCRIPTS -->
	<script type="text/javascript" src="./js/less.min.js"></script>
	<script type="text/javascript" src="./../vendor/videojs/video.js"></script>
	<script type="text/javascript" src="./../vendor/videojs/plugins/Youtube.js"></script>
	<script type="text/javascript" src="./../vendor/videojs/plugins/videojs-vimeo.js"></script>
	<script type="text/javascript" src="./../vendor/videojs/plugins/videojs.hotkeys.js"></script>
	<script type="text/javascript" src="./../dist/tmp/afterglow-bundle.js"></script>

    <!-- <script type="text/javascript" src="./../dist/afterglow.min.js"></script> -->
</head>
  <body>
	<style>
		body{
			max-width:700px;
			margin: 0 auto;
			padding-top: 50px;
            background:red;
		}
	</style>
    <video class="afterglow" id="myvideo" width="700" height="394"
     poster="./../video/Snapshots/afterglow_local.jpg" preload="none">
      
      <source src="./../video/MP4/afterglow_local.mp4" type="video/mp4" />
    </video>
  </body>
</html>
```
Not a successful build of the project
http://docs.afterglowplayer.com/docs/build-your-own

![5](https://user-images.githubusercontent.com/3471892/83304031-c497af00-a206-11ea-8fb8-cb9ebf06b484.png)

**Comment by moay** [comment]
Sorry man, I REALLY dont have time for this... https://www.google.com/search?q=primordials+is+not+defined
Probably the first answer.

**Comment by andrecool-68** [comment]
@moay Thank you very much for your help!
The very first link helped me fix this error!
It was necessary to create a new npm-shrinkwrap.json file
```
{
  "dependencies": {
    "graceful-fs": {
      "version": "4.2.3"
    }
  }
}
```
Successful assembly of the project!
P.S.
After building the project, the "dist/tmp/" directory is automatically deleted. 
How can I save this directory with temporary files?

Thank you for your patience and understanding)))

**Comment by andrecool-68** [comment]
@moay 
To save the directory with temporary files, I commented out this line in the file `gulpfile.js`
```
gulp.task('cleanup-tmp',['build-afterglow'], function(){
	// return del(['./dist/tmp']);
});
```
Is this temporary option a big mistake?

**Comment by moay** [comment]
For the last time. I'm very sorry, but I do NOT have the time to support you. You should either learn to develop or pay someone who knows what she/he's doing. Existing build scripts tend to have been implemented with some kind of purpose, but in the end it's up to you to change it or not. If it fails, you might at least learn something from it. :-)
