### ISSUE TITLE
Resolution switching breaks in some situations

### ISSUE THREAD

**Issue by moay** [moay/afterglow#16]
See https://community.afterglowplayer.com/d/24-resolution-switching-problems for more information

**Comment by moay** [comment]
Also, there should be a better HD Button

**Comment by Martin-Pitt** [comment]
I'd love to see a dropdown segmented control for a quality/resolution switcher.
These are rocksolid UI components that are easy to comprehend the state of.

**Comment by moay** [comment]
Sorry, this is a decision by design. The player will for now stay as simple as possible while providing professional features. I agree with you in that more than two resolutions could be part of a professional solution, but we won't (for now) change that. maybe for v2... ;-)
