### ISSUE TITLE
Add support for vidme videos

### ISSUE THREAD

**Issue by anonsubmitter** [moay/afterglow#19]
Can you add support for videos from [vidme](https://vid.me/)?

**Comment by moay** [comment]
Hi @anonsubmitter,

actually, that probably won't be possible. As far as I can see, vid.me does not provide any way to embed videos. The api needs OAuth, that would mean, that every user needed to allow the video access and have a vid.me account.

Maybe I'm wrong? Is there a way to embed videos from vid.me?

**Comment by anonsubmitter** [comment]
> Doing something cool? Need help?
Let's chat! Email us with any questions you have about the [API](https://vid.me/feedback). If you're doing something cool, let us know — we'd love to help you show it off!
Source: https://vid.me/api

**Comment by moay** [comment]
Yes, I'm aware of that api. The problem is, that it uses OAuth. This won't work without forcing everyone  to really do a lot work before using it. That's not what afterglow was made for... ;-)

in case you don't know how OAuth works, I'd recommend this explanation: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

**Comment by anonsubmitter** [comment]
What I meant is that you could maybe contact vidme and ask them for help. :)

**Comment by moay** [comment]
Sorry, but creating a public API is huge work. From a dev perspective, that's really not cool to ask - but hey, it's an open source project, don't hesitate to contribute! :-)

**Comment by anonsubmitter** [comment]
I didn't mean that you should build an API, just ask them they have any plans to make embedding easier.

I just found this. Does this help?
> We've decided to start working on an embeddable widget with a follow button and video stats. We might build this out into an embeddable playlist/album soon. Thanks again for the kind feedback, and please keep it coming :)

Source: https://www.reddit.com/r/vidme/comments/40w5zk/embeds/
