### ISSUE TITLE
Add support for Dailymotion videos

### ISSUE THREAD

**Issue by anonsubmitter** [moay/afterglow#20]
Can you add support for videos from [Dailymotion](http://www.dailymotion.com/)?

**Comment by moay** [comment]
That might be possible, we'd need to write a tech for video.js for that. Vimeo is higher on the list, but maybe anyone has already done that?

**Comment by moay** [comment]
There actually is a tech... https://github.com/benjipott/video.js-dailymotion Will take a look at this tomorrow.

**Comment by moay** [comment]
Library is not usable for vjs 5.6 for now. Sadly, this ain't possible for the moment. Maybe later.

**Comment by anonsubmitter** [comment]
Ok, thanks for looking into it.
