### ISSUE TITLE
Add support for videos from Streamable

### ISSUE THREAD

**Issue by anonsubmitter** [moay/afterglow#21]
I recently found a video hosting site called [Streamable](https://streamable.com/) and I think it looks pretty nice. Do you think adding support for it would be worth it?

**Comment by moay** [comment]
Actually, I'd love to support as many playing techs as possible, but sadly, most of them don't want to be embeddable. There is an API for streamable (https://streamable.com/documentation), but there is no tech available for videojs.

I will start to create some techs one day, but I currently have too many projects to do that right now.. Maybe you can start one?

**Comment by anonsubmitter** [comment]
I can't program, so unfortunately I can't help you with that.

**Comment by moay** [comment]
Closed for now, maybe we'll add this tech later.
