### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by SirNovi** [moay/afterglow#22]
autoplay="autoplay" is in the video tag in the source code and it works if JS is turned off, it doesn't work if JS is turned on and afterglow is kicking in. 

Side note: Sign Up for the community forum is not working (tried in chrome and firefox)

**Comment by moay** [comment]
Autoplay works fine for me, tested with Chrome and Firefox. Do you have a link to a site where I could have a look?

If the signup doesn't work for you, please try a stronger password. Sorry for that, the forum software is still in beta... ;-)

**Comment by DeeJaVu** [comment]
same here autostart doesnt work

**Comment by moay** [comment]
Hi @DeeJaVu 

Does still work for me - do you have link or can you describe your problem in more detail?
