### ISSUE TITLE
YouTube iframe API should not be loaded automatically

### ISSUE THREAD

**Issue by SirNovi** [moay/afterglow#23]
It does not seem like a good approach to always make a connection to the youtube server to load the iframe api which then loads another file from another source, even if none of it is needed.

**Comment by moay** [comment]
Hi @SirNovi!

Actually, this is the way how the YouTube API works. You should blame them for not creating good APIs...

**Comment by SirNovi** [comment]
For the second step the youtube API is to be blamed. But do you really need to load the YT API in the first place if there's no need for it?

**Comment by moay** [comment]
Sorry, I guess I didn't get you right. Sorry for that, my english is not perfect. ;-) Yes, you are totally right. 

I'll take a look into it.

**Comment by SirNovi** [comment]
No Problem. It's not my mother tongue either. 

Thanks for looking into it.
