### ISSUE TITLE
Doc: add alert not to add afterglow-* class to video element when using with lightbox

### ISSUE THREAD

**Issue by pandada8** [moay/afterglow#29]

**Comment by moay** [comment]
Hi @pandada8,

sorry, I've been out of office for a few days. I actually can't really get what you are trying to tell me. :-) What do you think should exactly be changed - and why?

**Comment by pandada8** [comment]
I happened to add .afterglow class to the video, and when click the <a> link, just got `this.el_.play is not a function` error, and then after reading code of the afterglow and videojs I just realize the original video element is a Play instance already now, and just being wrapped again. Maybe you could add some alert in lightbox's document to let others know ?

**Comment by moay** [comment]
Actually, this is already in the documentation: http://docs.afterglowplayer.com/docs/lightbox-player#setup. It states clearly, that the video element should **not** get the class `afterglow` but the trigger element. 

Also there is an alert with the headline "Class goes to the link, not to the player".

Doesn't this match your recommendation?
