### ISSUE TITLE
Network request to youtube.com/iframe_api regardless of video type

### ISSUE THREAD

**Issue by 10bass** [moay/afterglow#39]
I have a self-hosted v1.0 player instance with a single mp4 video source that is served from another domain. There is no 'data-youtube-id' defined, but when the player loads it still makes a call to https://www.youtube.com/iframe_api.

This call will start failing when I enable CSP headers for the site, so maybe it won't be an issue, but is that the expected behavior - that it pulls JavaScript from YouTube on every video load regardless of the source?
It looks like this call originates with the video.js YouTube plugin. Should I instead open an issue there?

**Comment by moay** [comment]
Hi. :-)

I can't reproduce this behaviour. Just compare the calls to the project website - there is no call to youtube, if you don't actually have a youtube video on your page. The Youtube tech is not loaded, if you don't play a Youtube video somewhere. Do you have a link to your page so that I could take a look?

**Comment by 10bass** [comment]
Hi, thanks for taking a look. Hm, odd. I get the same call happening for the lightbox example, which is how I'm presenting the video. (http://docs.afterglowplayer.com/docs/launching-in-a-lightbox) I see the request on the docs page in Firefox and Chrome on two different PCs on two separate networks, so I'm not sure what would be triggering it.

An example page would be here: https://www.bowenehs.com/computer-member-center/connecting-to-the-virtual-classroom-electa.html

**Comment by moay** [comment]
Yes, confirmed. That is strange, indeed. I'll look into it.

**Comment by moay** [comment]
Fixed that by deferring youtube initialization to the moment where the player is actually initialized.
