### ISSUE TITLE
Opening Lightbox stops other videos

### ISSUE THREAD

**Issue by andreipan** [moay/afterglow#40]
In some situation there is no need in such a behaviour. For e.x. there is a background video without any controls and popup video on the same page. After opening lightbox backgroud video stops without posibility to start again.

**Comment by moay** [comment]
Yes, that is accurate, but actually, afterglow should only stop videos that it controls. Is the background video played via afterglow?

**Comment by andreipan** [comment]
In my case all the videos playing via afterglow.
The following code stops it
`
for(let key in window.videojs.getPlayers()) {
    if(window.videojs.getPlayers()[key] !== null && window.videojs.getPlayers()[key].id_ !== this.playerid)
    {
		    	window.videojs.getPlayers()[key].pause();
    }
}
`

**Comment by moay** [comment]
Actually, the behaviour is intended and important for mobile devices. Most of them might encounter a breakdown when trying to render two playing videos at the same time. But there is a quite simple way to fix your problem using the new events:

    afterglow.on('#lightboxPlayerId', 'lightbox-closed', function() {
        afterglow.getPlayer('backgroundPlayerId').play();
    });

Is this an option for you?

**Comment by andreipan** [comment]
I will test it. 
Thanks for quick response!
