### ISSUE TITLE
please deliver AIRPLAY - Button

### ISSUE THREAD

**Issue by skerbis** [moay/afterglow#41]
```
// Detect if AirPlay is available
if (window.WebKitPlaybackTargetAvailabilityEvent) {
    video.addEventListener('webkitplaybacktargetavailabilitychanged', function(event) {
        switch (event.availability) {
            case "available":
                AirPlayButton.show();
                break;
            default:
                AirPlayButton.hide();
        }
        AirPlayButton.on('click', function() {
            video.webkitShowPlaybackTargetPicker();
        });
    });
}
```

**Comment by moay** [comment]
This is currently not on the list, as it affects too few people and it should be an OS/browser feature. If there is something to be streamed, the OS (or the browser) should provide the functionality and a button (via notification). On top of that, we'd need to include a new plugin for video js which would increase the file size even more.

Feel free to provide a PR, we'll see if we can integrate it.

**Comment by moay** [comment]
Addition to the above: In order to fix the missing OS/browser buttons, here is a Bookmarklet which could provide the functionality for you: https://bendodson.com/weblog/2011/01/13/enabling-any-html5-video-to-work-over-airplay-e-g-vimeo/

Not tested with afterglow - let me know if this does the trick.

**Comment by skerbis** [comment]
It does the trick, yes sure. But iOS and Mac-Users (this is not a few group of people) would love to see this feature. btw. we've integrated Afterglow in our REDAXO Video AddOn 👍  https://github.com/FriendsOfREDAXO/video, hope you like it. Today we will update it to the current release
