### ISSUE TITLE
Can't install afterglow with bower

### ISSUE THREAD

**Issue by drnkwati** [moay/afterglow#42]
I have this error when installing afterglow with bower
Unexpected token ] in JSON at position 490
can you verify this please

**Comment by moay** [comment]
@simonhdickson fixed that. Thanks! I'll push a new release tomorrow, just to make sure bower works fine everywhere.

**Comment by drnkwati** [comment]
Still not installing with bower. I get the same error massage

**Comment by moay** [comment]
Sorry, I did't find the time to draft a release yesterday. I'll try to do this today.

Please use this command for a quick fix:

    bower install afterglow@master

**Comment by moay** [comment]
Release is out, should work again as soon as all the cache clear...
