### ISSUE TITLE
Lightbox mode does not work with youtube videos

### ISSUE THREAD

**Issue by mruvim** [moay/afterglow#45]
Player setup:

```
<a class="afterglow" href="#myvideo">Launch lightbox</a>
<video id="myvideo" width="960" height="540">
    <source data-youtube-id="{youtube-id}" data-overscale="false" />
</video>
```

Expected result: Should play youtube video in Lightbox mode
Actual result: Video does not load
Browser: Safari 11.0.1

**Comment by moay** [comment]
`data-youtube-id" is not a parameter that can be added to source as youtube provides the sources itself.

Try to fix your setup by changing it to this:

```
<a class="afterglow" href="#myvideo">Launch lightbox</a>
<video id="myvideo" width="960" height="540" data-youtube-id="{youtube-id}" data-overscale="false"></video>
```

Let me know if this helped.

**Comment by mruvim** [comment]
This works, thank you!
