### ISSUE TITLE
Afterglow video on seek makes IE not responding

### ISSUE THREAD

**Issue by brystfire08** [moay/afterglow#50]
Hi.

When i used the afterglow js plugin for my video IE hangs when sliding the slider unlike when I am not using the plugin. Any way to fix this? Thanks in advance. Nice plugin btw

**Comment by moay** [comment]
Hi.

Please provide more information. Which version of IE? Which slider? Any Javascript errors in the console?

It's always easier with a link to your problem provided so we can look into the source. :-)

**Comment by brystfire08** [comment]
Hello sorry for the late response..

There is nothing special in the code except that it is inside an iframe.

I am using IE 11 and tried it in IE 10 and it happened their too. The slider that I am talking about is the slider in video to adjust the current frame the video is playing.

I tried to play another video which is also in mp4 format and it does not happen their.. I am not sure if it is because of the video encoding but both works without problems in the native HTML 5 video player.

Ill just put a sample video details here: 

1st video where problem does occur:
Dimensions: 640x360
Length: 33 seconds
Frame rate : 25 frames per second
Data rate :  791 kbps
Total Bit rate: 922 kbps
Audio Bit rate : 130 kbps

2nd video where the problem does not happen:
Dimensions: 428x320
Length: 2 minutes 20 seconds
Frame rate : 15 frames per second
Data rate :  176 kbps
Total Bit rate: 272 kbps
Audio Bit rate : 130 kbps

There is a noticeable difference in quality of two videos where in the 1st one is too low.

So yeah that's it. For now I am using the default player.

**Comment by moay** [comment]
IE support will be dropped.
