### ISSUE TITLE
Weird behaviour when loading of https://fonts.googleapis.com is prevented

### ISSUE THREAD

**Issue by micr0lab** [moay/afterglow#51]
Hi,

This behavior is not easy to reproduce, but let me try to explain what I believe is the problem.

We can use [Content Security Policy](https://content-security-policy.com/) to prevent resources from being loaded from non-approved sites. The quick reference guide reads

> The new Content-Security-Policy HTTP response header helps you reduce XSS risks on modern browsers by declaring what dynamic resources are allowed to load via a HTTP Header.

If you set the default policy to `* 'unsafe-inline' 'self' 'unsafe-eval' data` ( = basically load anything from anywhere is the default behavior) but restrict the style to `'self' 'unsafe-inline'` (= load the style only from the same server, and allow inline style), then everything loads perfectly, except for `https://fonts.googleapis.com/css?family=Open+Sans:400,300`. This is the expected behavior.

 The strange part is that, this will prevent afterglow from working completely. The video loaded from vimeo or youtube won't be displayed, **no** style will be applied, and what will be served is just the plain `video` html element.

This behavior is difficult to reproduce. You can see it live at https://micr0lab.org/mu0l_0092/, I tried to reproduce it with the following minimal example:

```
<!DOCTYPE html>
<?php header("Content-Security-Policy: default-src * 'unsafe-inline' 'self' 'unsafe-eval' data;: style-src 'self' 'unsafe-inline'"); ?>
<html>
  <head>
    <title>afterglow player</title>
    <script src="afterglowplayer.js"></script>
  </head>
  <body>
   <video class="afterglow" width="1280" height="720" data-vimeo-id="238388144">
      <source type="video/mp4" src="L_eau_croupie_et_les_fantasmins.mp4" />
    </video>
  </body>
</html>
```

that you can test live at https://micr0lab.org/t/, but it doesn't exactly show the same weird behavior.

**Comment by micr0lab** [comment]
Oh, and BTW, the reason I'm trying to document that bug is because when I [self-host afterglow](http://docs.afterglowplayer.com/docs/self-hosting-afterglow), I'd like to allow only connections to youtube and vimeo, not to other third-party websites.

**Comment by micr0lab** [comment]
I guess that, stated differently, my bug is that I'd like to be able to easily remove the loading of resources at https://fonts.googleapis.com/

**Comment by moay** [comment]
Feel free to change this and build your own version. Alternatively, you could just allow fonts.googleapis.com in your server or include the loaded fonts via javascript yourself (which would prevent the deferred loading).
