### ISSUE TITLE
attach afterglow only in newest elements (infinitescroll)

### ISSUE THREAD

**Issue by lgugliotta** [moay/afterglow#55]
How can I Call again afterglow, but only the newest elements. I using a infinite scroll but when I do afterglow.init(), the old elements are attached twice afterglow

**Comment by moay** [comment]
Sadly, thats not so easy to do. It is of course possible, but you shouldn't need to do it.

Here is the relevant part of the things that happen, when you call `afterglow.init()`: https://github.com/moay/afterglow/blob/efc788e0ba070ad5208f5a631dda55f60a0bb9a0/src/js/afterglow/Afterglow.js#L68

Mimic this behaviour for just what you want to do, and voilà. Sadly I don't have the time to provide a proper solution right now, should be easily doable with something like `afterglow.init('my-video-id')`, but that nees to be setup.

**Comment by moay** [comment]
Closed in favor of #63
