### ISSUE TITLE
Prevent Video MP4/ Youtube from being paused.

### ISSUE THREAD

**Issue by glennthornton** [moay/afterglow#56]
I could not find this in the docs. How do you prevent the video from being paused? I already removed all the player controls.. I just need to prevent the users from clicking the video to stop/pause it. Here is code I tried to use... 

.vjs-afterglow-skin .vjs-play-control {
    pointer-events: none !important;
}``

**Comment by moay** [comment]
Sorry, late response 😬. This is not possible, I think, as this is unintended behaviour. It is (by law of politeness) forbidden to steal peoples bandwidth or data volume, so doing this is not advised. Afterglow can't provide the feature, but you could try overlaying a transparent something. Probably this won't work on mobile.
