### ISSUE TITLE
Sign up for the forum (community.afterglow.com) seems not work

### ISSUE THREAD

**Issue by DoraPaula** [moay/afterglow#57]
I would like to ask a question on the afterglow forum, but can't sign up, there:

I entered a login, my e-mail address and a password, clicked the button .... but nothing seems to happen, at least: I get not e-mail message. And I don't get any error-message (next to firefox's warning regarding the servers certificate).  I tried it three to four times (with varying login and password), without success.

I'm sorry for this report/support-request, but I could not find any other contact address.

**Comment by moay** [comment]
Hi there,

sorry for that. I don't have much time to put into the project right now, I'll  look into it as soon as I can.

**Comment by DoraPaula** [comment]
Thanks a lot!
