### ISSUE TITLE
How to add videojs plugins

### ISSUE THREAD

**Issue by supersh86** [moay/afterglow#70]
hello how to add other videojs plugins?
I'm interested in adding cdnbye
https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/docs/English/API.md
(Need hls object variable)

And Vast Ad Plugin

**Comment by moay** [comment]
Hi there,

don't, we are currently switching away from video js. v2 is in the makings and will support hls (at least basically). Ads will not be supported for now, as this does interfere with youtube and vimeo tos.

Anyways, feel free to get the raw sourcecode of afterglow and add your plugins there. :-)

Greetings from germany
