### ISSUE TITLE
Can use videojs-resolution-switcher plugin with this? for more quality change?

### ISSUE THREAD

**Issue by ahmadshc** [moay/afterglow#71]
Hello, thank you for create this pretty simple player
Can use videojs-resolution-switcher plugin with this? for more quality change?
this version of plugin (work correct with latest version videojs 7.3):
**[videojs-resolution-switcher](https://github.com/razzbee/videojs-resolution-switcher)**

**Comment by moay** [comment]
We are switching away from video.js, so I'll not provide a solution. But you could easily build your own version of afterglow with advanced resolution switching capabilities. Read the docs for more info on this

**Comment by ahmadshc** [comment]
> We are switching away from video.js, so I'll not provide a solution. But you could easily build your own version of afterglow with advanced resolution switching capabilities. Read the docs for more info on this

Thank you very much for your answer, i'm not a programmer. i can't do it in time. good luck.
