### ISSUE TITLE
Preload Attribute not working correct in afterglow

### ISSUE THREAD

**Issue by ahmadshc** [moay/afterglow#72]
Hello
html5 preload attribute not working in afterglow player
here is my code:
`
<video class="afterglow" id="myvideo2" data-skin="dark" width="1280" height="720" preload="metadata">
      <source type="video/mp4" src="480p.mp4" />
      <source type="video/mp4" src="1080p.mp4" data-quality="hd"/>
</video>
`

**Comment by moay** [comment]
Preload is not a very reliable attribute, browsers tend to do what they want with it - in my experience, the preload attribute is ignored most of the times.

This is an html5 video tag thing and has nothing directly to do with afterglow. Read more on this here: https://www.w3schools.com/tags/att_video_preload.asp

**Comment by ahmadshc** [comment]
> Preload is not a very reliable attribute, browsers tend to do what they want with it - in my experience, the preload attribute is ignored most of the times.
> 
> This is an html5 video tag thing and has nothing directly to do with afterglow. Read more on this here: https://www.w3schools.com/tags/att_video_preload.asp

All of desktop browsers default support preload attribute, and mobiles too (Until the optimal data saver mode on mobile is active)
Anyway
If this feature is supported on your player, that's great
VideoJS, Plyr, FluidPlayer, JWplayer and more support as well this feature (preload attribute)
Accept this as a suggestion from me
Thank you

**Comment by moay** [comment]
Again: you are applying the attribute to a regular video tag. Afterglow doesn't change that, so if the attribute is ignored, you'll most likely want to look for other possible causes. To name just a few:

- used browser
- number of windows that are open at the same time
- available bandwidth
- proper cors or other headers
- media encoding

There are many more possible causes for the attribute being ignored - afterglow should not be one of them.
