### ISSUE TITLE
Can change HD label to FHD ?

### ISSUE THREAD

**Issue by ahmadshc** [moay/afterglow#73]
Hello and thank you for pretty afterglow
Can change HD label to FHD or Full HD ?
I need it, please help me
Thank you

**Comment by moay** [comment]
Not as part of the player, but you can do this via CSS - just provide your own icon if you need one.

**Comment by TuxMay** [comment]
Maybe add support for multiple resolutions so we can have SD, HD, FHD & UHD - Adding support for different resolutions will bring solve everything?

**Comment by moay** [comment]
This is not on the list. Feel free to submit a pr. :-)

**Comment by TuxMay** [comment]
I'm not a developer, but offering multiple resolutions should be standard for a video player.

**Comment by moay** [comment]
Feel free to improve your skills and develop your own player matching your standards. Or pay for a player that has everything you need.

**Comment by TuxMay** [comment]
I'm not paying $800/mo for a player that fits my standards. It was a recommendation, no need to be rude.
