### ISSUE TITLE
Play, Pause not working on video screen in lightbox

### ISSUE THREAD

**Issue by sagarthakar** [moay/afterglow#77]
When a video is playing inside a lightbox, then when we click on the video screen for pause, or play then that click is not identified and it doesnt pause or plays the video.

This works when we embed the video in a page, but it doesnt in lightbox.

**Comment by sagarthakar** [comment]
I used v2 alpha6, v2 alpha8, also i checked on v1.1x the on screen play/ pause click is not identified on chrome, safari, firefox.

Is there any data tag i need to pass for this ?

**Comment by sagarthakar** [comment]
Let me check again at my end. I will re-confirm if this works

**Comment by moay** [comment]
No tags are needed, everything in afterglow is oob... ;-) Just tested, works flawlessly in Safari and Chrome for me. Maybe you have other issues in your page, watch out for javascript errors.

Closing this, as I believe it's not actually related to afterglow, feel free to reopen it, if the issue remains.
