### ISSUE TITLE
Ability to add html overlay

### ISSUE THREAD

**Issue by sagarthakar** [moay/afterglow#80]
Hi,

Please provide ability to provide html overlay on video, i tried using custom code but it does not work when we use afterglow class in the video syntax.

It will be helpful if you can provide ability to add html overlay.

Thanks

**Comment by moay** [comment]
For v1, this is not that easy. Doable, but not that easy. Steps:

- Wait for the play event (or ready, whichever you need)
- Find the player instance
- Do whatever you want with the node.

Something like this:

```javascript
afterglow.on('myPlayer', 'play', function() {
    // Find the current player node and do whatever you like
} 
```

For v2, it'll be easier. The node will be ready within the player instance:

```javascript
afterglow.on('myPlayer', 'ready', function(event) {
    var nodeYouAreLookingFor = event.instance.mediaelement.container.node;
    // Append your stuff to the container
} 
```

In both cases you'll want to know what you are doing in javascript.

Closed, as this is not an issue but a help request. Please consider making help requests in the community.
