### ISSUE TITLE
Video does not load - only in Chrome

### ISSUE THREAD

**Issue by wgruenberger** [moay/afterglow#84]
Hi,

we have a strange issue - we are using Afterglow coming with the Video add-on from CMS redaxo here:
https://www.netfiles.de/
(only in German, click "Film ansehen" below the laptop-screen ;-)
The video loads fine in IE and Firefox but does not load in Chrome.
Do you have any idea what's happening here?

Thank you, Werner.

**Comment by moay** [comment]
That's strange, seems to be related to youtube. There currently is a problem with v1 and youtube, but it's mostly related to multiple videos on the same page.

Are you able to test v2? Should be drag and drop.

**Comment by wgruenberger** [comment]
v2 fixes the problem, thank you
Hope we'll not get too crazy with the alpha release ;-)

**Comment by moay** [comment]
Great. Let me know if you encounter any issue. There currently seem to be some problems with mobile devices - could you test for this use case? Feedback welcome.

**Comment by wgruenberger** [comment]
one little thing, on pause there are "Weitere Videos" (engl.: more videos?) shown. I assume there is a data-attribute at the video-element to deactivate that?

**Comment by moay** [comment]
No, youtube does not allow to disable that any more, as far as I can see. There have been some changes to how their "iframe api" works (it's quite buggy overall), in newer use cases, we have not been able to find a solution for this. :-(

**Comment by wgruenberger** [comment]
Ok, thank! For me the issue is fixed
(although we have one more reason to think about hosting the video on our own server ;-)
