### ISSUE TITLE
pause and Play API

### ISSUE THREAD

**Issue by ShaimaaHamdan** [moay/afterglow#85]
Hello , at first load to my application then i open one video then stop it then play it again it work perfectly after that i switched to another video play and pause not work any more , btw i use the same html video element when i switch to another video i just change the source . any help ?

**Comment by moay** [comment]
I you have a link for me in order to investigate the issue? There are many possible reasons for the problem, it's not possible to tell you anything without actually seeing the problem.

Please provide a link to your site. You can also do so via email (afterglow[at]moay.de).

**Comment by ShaimaaHamdan** [comment]
Hello Thanks for your reply , actually we don't have a public url but i discovered the issue yesterday looks like the when i change the video src from video to video it is cashing the old video in fomation in afterglow so i have to  use afterglow.destroyPlayer('xxxx'); to destroy the element before using it again !
thanks again ! and by the way it is very good library but with bad documentations i have to dig in to the code it self to find the destroy function name ! but keep going ! 
thanks !
