### ISSUE TITLE
Video Resolution

### ISSUE THREAD

**Issue by ShaimaaHamdan** [moay/afterglow#87]
Hello , I have a question regarding Video Resolution , when i start playing video it loads with low resolution for 3 or 4 sec , i don't know why is there is any configuration for that i can play with it ?
thanks

**Comment by moay** [comment]
Just put the HD source first. Should do the trick. If it doesn't, you might want to check the loading times of your sources, maybe your server behaves strangely here or it actually provides lower bandwidth to speed up initial playback.

**Comment by ShaimaaHamdan** [comment]
i have just one url for the source , so can you please show me how ?

**Comment by moay** [comment]
Please read the docs. Everything ist described there. http://docs.afterglowplayer.com/docs/video-sources
