### ISSUE TITLE
Remove shadow inside player when adding poster or background-image

### ISSUE THREAD

**Issue by gperozzo** [moay/afterglow#97]
Hello,

After I add a ```poster``` or a ```background-image``` property to the ```video``` tag, a strange shadow is added to the video player.

How can I remove that?

```
<div class="video-style m-t-70" style="margin-bottom:20px!important;">
     <video class="afterglow" id="myvideo" width="1000" height="563" style="background-image:url(img/img_video_thumb2.png);">
            <source type="video/mp4" src="video/video.mp4" data-quality="hd" />
     </video>
</div>

.video-style {
    width: 1000px;
    border-radius: 5px;
    overflow: hidden;
    box-shadow:none!important;
}

```
![sample](https://user-images.githubusercontent.com/4451967/63891654-18e1da00-c9bc-11e9-93a5-c5eb4764fbdf.PNG)

**Comment by moay** [comment]
Just tried both poster and background image. See https://codepen.io/pen?template=EKqPNL

It's not related to afterglow, check your other scrips and styles for one that might add the shadow.
